version: 2.1
workflows:
 test-deploy:
   - test:
jobs:
  test:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo yum update && sudo yum  install -y httpd*
      
